-- Create properties table for real estate platform
-- This script creates only the properties table without affecting existing tables

CREATE TABLE IF NOT EXISTS `properties` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `externalId` varchar(128),
  `addressLine1` varchar(255) NOT NULL,
  `addressLine2` varchar(255),
  `city` varchar(100) NOT NULL,
  `state` varchar(50) NOT NULL,
  `zipCode` varchar(20) NOT NULL,
  `country` varchar(50) NOT NULL DEFAULT 'USA',
  `latitude` varchar(20) NOT NULL,
  `longitude` varchar(20) NOT NULL,
  `propertyType` enum('single_family', 'condo', 'townhouse', 'multi_family', 'land', 'commercial') NOT NULL,
  `listingType` enum('sale', 'rent', 'sold', 'off_market') NOT NULL,
  `status` enum('active', 'pending', 'sold', 'off_market', 'archived') NOT NULL DEFAULT 'active',
  `bedrooms` int,
  `bathrooms` int,
  `squareFeet` int,
  `lotSize` int,
  `yearBuilt` int,
  `price` int NOT NULL,
  `pricePerSqFt` int,
  `title` varchar(255),
  `description` text,
  `features` text,
  `primaryImage` text,
  `images` text,
  `virtualTourUrl` text,
  `listDate` timestamp NULL,
  `soldDate` timestamp NULL,
  `daysOnMarket` int,
  `viewCount` int DEFAULT 0,
  `ownerId` int,
  `agentId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_city` (`city`),
  KEY `idx_status` (`status`),
  KEY `idx_price` (`price`),
  KEY `idx_propertyType` (`propertyType`),
  KEY `idx_coordinates` (`latitude`, `longitude`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
